name: Deploy to EC2 with Safe Folder Switch

on:
  push:
    branches:
      - main  # или своя ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "~/lms-prog-academy-lesson9-10-dz-docker/pwa_"

      - name: SSH and deploy safely
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/lms-prog-academy-lesson9-10-dz-docker

            if [ -d "pwa__" ]; then rm -rf pwa__; fi
            
            if [ -d "pwa" ]; then mv pwa pwa__; fi

            
            if [ -d "pwa_" ]; then mv pwa_ pwa; else echo "❌ Ошибка: pwa_ не найдена"; exit 1; fi
            
            docker compose exec -T frontend npm install || true
            
            docker compose restart frontend
